### ISSUE TITLE
Add cloning to better support composing pipelines?

### ISSUE THREAD

**Issue by cspital** [codegangsta/mixer#3]
Hi there,

I really like the design of this package. I added cloning to better support composing pipelines, for example:
Default mixer (log request start, assign traceId)
Authenticated mixer (fetch a user and 401 if user not found)
Authorized mixer (apply an authorization policy to user and 403 if fail etc)

Would you be open to a PR (I didn't want to PR new stuff in out of the blue)?

**Comment by codegangsta** [comment]
Cloning was one of the things I was thinking of adding next, so you beat me to it! Feel free to put up a Pr. Thanks so much

**Comment by cspital** [comment]
The only thing that doesn't quite lend itself to composition right now is the way after hooks are executed. Executing them forwards means that any middleware expected to run on ALL mixers would have to register them last on each copy. Reversing the execution order of after hooks would resolve this and should be pretty intuitive from a usability standpoint.

**Comment by codegangsta** [comment]
Yup. Totally get it. I think for now this implementation in #4 is simple and readable enough to know what it is doing. Appreciate the contribution! merged #4
